export const btnRegV: string;
export const btn: string;
export const btn2: string;
export const btnTxt: string;
export const label: string;
export const labelTxt: string;
export const container: string;
export const containerStyle: string;
export const labelform: string;
